import type { ScriptConfig } from '../types';

export function generateScript(config: ScriptConfig): string {
  const lines: string[] = [];

  lines.push('#!/bin/bash');
  lines.push('');
  lines.push('# Auto-generated server configuration script');
  lines.push('# Generated by ScriptGen');
  lines.push('');
  lines.push('set -e');
  lines.push('');
  lines.push('echo "Starting server configuration..."');
  lines.push('');

  if (config.groups.trim()) {
    lines.push('# Create groups');
    const groupList = config.groups.split(',').map(g => g.trim()).filter(Boolean);
    groupList.forEach(group => {
      lines.push(`if ! getent group ${group} > /dev/null 2>&1; then`);
      lines.push(`  groupadd ${group}`);
      lines.push(`  echo "Created group: ${group}"`);
      lines.push('else');
      lines.push(`  echo "Group ${group} already exists"`);
      lines.push('fi');
    });
    lines.push('');
  }

  if (config.users.trim()) {
    lines.push('# Create users');
    const userList = config.users.split(',').map(u => u.trim()).filter(Boolean);
    userList.forEach(user => {
      lines.push(`if ! id -u ${user} > /dev/null 2>&1; then`);
      lines.push(`  useradd -m -s /bin/bash ${user}`);
      lines.push(`  echo "Created user: ${user}"`);
      lines.push('else');
      lines.push(`  echo "User ${user} already exists"`);
      lines.push('fi');
    });
    lines.push('');
  }

  if (config.hostname.trim()) {
    lines.push('# Set hostname');
    lines.push(`hostnamectl set-hostname ${config.hostname}`);
    lines.push(`echo "${config.hostname}" > /etc/hostname`);
    lines.push(`echo "Hostname set to: ${config.hostname}"`);
    lines.push('');
  }

  if (config.firewallRules.length > 0) {
    lines.push('# Configure UFW firewall');
    lines.push('if ! command -v ufw &> /dev/null; then');
    lines.push('  echo "UFW not found. Installing..."');
    lines.push('  apt-get update && apt-get install -y ufw');
    lines.push('fi');
    lines.push('');

    const validRules = config.firewallRules.filter(rule => rule.port.trim());
    validRules.forEach(rule => {
      lines.push(`ufw ${rule.action} ${rule.port}/${rule.protocol}`);
      lines.push(`echo "Firewall rule added: ${rule.action} ${rule.port}/${rule.protocol}"`);
    });
    lines.push('');
    lines.push('ufw --force enable');
    lines.push('echo "UFW firewall enabled"');
    lines.push('');
  }

  if (config.sshPort.trim() || config.disableRootLogin) {
    lines.push('# Configure SSH');
    lines.push('SSH_CONFIG="/etc/ssh/sshd_config"');
    lines.push('');

    if (config.sshPort.trim() && config.sshPort !== '22') {
      lines.push(`sed -i 's/^#*Port .*/Port ${config.sshPort}/' $SSH_CONFIG`);
      lines.push(`echo "SSH port changed to: ${config.sshPort}"`);
    }

    if (config.disableRootLogin) {
      lines.push('sed -i \'s/^#*PermitRootLogin .*/PermitRootLogin no/\' $SSH_CONFIG');
      lines.push('echo "Root login disabled"');
    }

    lines.push('');
    lines.push('systemctl restart sshd');
    lines.push('echo "SSH service restarted"');
    lines.push('');
  }

  lines.push('echo "Server configuration completed successfully!"');

  return lines.join('\n');
}
